apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: podinfo
  interval: 5m
  retryInterval: 5m
  path: ./
  prune: true
  wait: true
  timeout: 2m
  images:
    - name: ghcr.io/203-cloud/demo-app
      newTag: latest
  patches:
    - target:
        group: apps
        version: v1
        kind: Deployment
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: MESSAGE
            value: "Hello from dev"