apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
  - demo-app-kustomization.yaml
patches:
  - target:
      kind: Kustomization
    path: values.yaml