apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  url: oci://sunbeamfluxacr.azurecr.io/artifact/podinfo
  provider: azure
  ref:
    tag: latest