apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: podinfo
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: PathPrefix(`/`) || Path(`/`)
      services:
        - name: podinfo-podinfo
          namespace: podinfo
          port: 9898