apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: podinfo
  targetNamespace: podinfo
  install:
    createNamespace: true
  values:
    ui:
      message: "Hello from the dev cluster"
