apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dummy
spec:
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        - op: add
          path: /spec/values/ui/message
          value: "Hello from staging"
    - target:
        kind: IngressRoute
        name: podinfo
      patch: |-
        - op: replace
          path: /spec/routes/0/match
          value: Host(`flux-staging.203.cloud`) && (PathPrefix(`/`) || Path(`/`))