apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - namespace.yaml
  - middleware.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml