name: Build release artifact for team-a flux configuration

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - '.github/workflows/build-team-config.yaml'

permissions:
  contents: read
  packages: write

jobs:
    latest:
        name: Build latest from main to dev
        if: github.ref == 'refs/heads/main'
        defaults:
            run:
                working-directory: ./deploy
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup flux
            uses: fluxcd/flux2/action@main
            with:
              version: latest
          - name: Build latest artifact
            run: |
                echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
                container_registry=ghcr.io/${{ github.repository }}
                flux push artifact oci://${container_registry}/flux-config:$(git rev-parse --short HEAD) \
                    --provider=generic \
                    --reproducible \
                    --path="." \
                    --source="$(git config --get remote.origin.url)" \
                    --revision="$(git branch --show-current)/$(git rev-parse HEAD)" || echo "Failed to push flux config" >&2
                flux tag artifact oci://${container_registry}/flux-config:$(git rev-parse --short HEAD) \
                    --provider=generic \
                    --tag dev || echo "Failed to tag flux config" >&2
          